server:
  port: 80

eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 客户端(服务提供者)注册到哪一个Eureka Server服务注册中心，多个用逗号分隔
      defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/
feign:
  hystrix:
    enabled: true #开启客户端熔断